budgets/urls.py
from django.urls import path

from budgets.views import budgets


app_name = 'budgets'

urlpatterns = [
    path('', budgets, name='budgets')
]


finances/urls.py
from django.urls import path

from finances.views import *

app_name = 'finances'

urlpatterns = [
    path('profile/', profile, name='profile'),
    # path('transaction/', transaction, name='transaction'),
    path('create_wallet', create_more_wallet, name='create_wallet'),
    path('update_wallet', update_wallet_data, name='update_wallet'),
    path('delete_wallet', try_delete_wallet, name='delete_wallet'),
    path('wallet_data', wallet_data, name='wallet_data'),
    path('transactions_per_day', transactions_per_day, name='transactions_per_day'),
    path('transactions_per_yesterday', transactions_per_yesterday, name='transactions_per_yesterday'),
    path('income/', income, name='income'),
    path('outline/', outline, name='outline'),
    path('report/', report, name='report'),
    path('report_per_day/', report_per_day, name='report_per_day'),
    path('report_per_week/', report_per_week, name='report_per_week'),
    path('report_per_month/', report_per_month, name='report_per_month'),
    path('logout/', logout, name='logout')
]


investing/urls.py
from django.urls import path

from investing.views import dashboard


app_name = 'investing'

urlpatterns = [
    path('', dashboard, name='dashboard')
]


main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login, name='login'),
    path('user/', include('users.urls', namespace='user')),
    path('finances/', include('finances.urls', namespace='finances')),
    path('pdf_gen/', include('pdf_gen.urls', namespace='pdf_gen')),
    path('investing/', include('investing.urls', namespace='investing')),
    path('budgets/', include('budgets.urls', namespace='budgets'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdf_gen/urls.py
from django.urls import path
from pdf_gen.views import *

app_name = 'pdf_gen'

urlpatterns = [
    path('pdf_generation/', pdf_generation, name='pdf_generation')
]

finances/models.py
from django.db import models
from users.models import User, Wallet


class TransactionCategory(models.Model):
    ico = models.ImageField(upload_to='categories-icons')
    name = models.CharField(max_length=30, primary_key=True)

    def __str__(self):
        return self.name


class Transaction(models.Model):
    type = models.BooleanField(default=False)  # True(+) False(-)
    sum = models.DecimalField(max_digits=14, decimal_places=2)
    date = models.DateField(auto_now=True)
    comment = models.TextField(null=True, blank=True)
    category = models.ForeignKey(to=TransactionCategory, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    wallet = models.ForeignKey(to=Wallet, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.date} | {self.user} | {self.category}'
    





finances/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm

from users.models import User, Wallet
from finances.models import Transaction


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Имя пользователя'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'readonly': 'True',
        'id': 'readonly'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'example@gmail.com'
    }))

    class Meta:
        model = User
        fields = (
            'first_name', 'username', 'email'
        )


class IncomeForm(forms.Form):
    CATEGORY_CHOICES = [('Зарплата', 'Зарплата'), ('Подарок', 'Подарок'), ('Другое', 'Другое')]

    sum = forms.DecimalField(widget=forms.NumberInput(attrs={
        'placeholder': 'Введите сумму'
    }))
    category = forms.ChoiceField(widget=forms.RadioSelect(attrs={
        'class': 'radio-currency'
    }), choices=CATEGORY_CHOICES)
    comment = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Напишите комментарий'
    }))
    
    class Meta:
        model = Transaction
        fields = (
            'sum', 'category', 'comment'
        )


class OutlineForm(forms.Form):
    CATEGORY_CHOICES = [('Образование', 'Образование'), ('Здоровье', 'Здоровье'), ('Дом', 'Дом')]

    sum = forms.DecimalField(widget=forms.NumberInput(attrs={
        'placeholder': 'Введите сумму'
    }))
    category = forms.ChoiceField(widget=forms.RadioSelect(attrs={}), choices=CATEGORY_CHOICES)
    comment = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Напишите комментарий'
    }))

    class Meta:
        model = Transaction
        fields = (
            'sum', 'category', 'comment'
        )


class CreateWalletForm(forms.Form):
    CURRENCY_CHOICES = [('BYN', 'BYN'), ('USD', 'USD'), ('EUR', 'EUR')]

    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Семейный\Личный счет'
    }))
    currency = forms.ChoiceField(widget=forms.RadioSelect(attrs={
    }), choices=CURRENCY_CHOICES)

    class Meta:
        model = Wallet
        fields = (
            'name', 'currency'
        )


class UpdateWalletForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Семейный\Личный счет'
    }))
    target = forms.BooleanField(widget=forms.CheckboxInput(attrs={

    }), required=False)
    class Meta:
        model = Wallet
        fields = (
            'name', 'target'
        )

finances/views.py
from django.shortcuts import redirect, render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages, auth

from finances.forms import *
from finances.services import *
from users.services import create_wallet


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Изменения применены!')
            return HttpResponseRedirect(reverse('finances:profile'))
        else:
            messages.warning(request, 'Что-то пошло не так!')
            return HttpResponseRedirect(reverse('finances:profile'))
    else:
        form = UserProfileForm(instance=request.user)

    user_data = request.user
    yesterday = request.session.get('yesterday')
    wallets = get_wallets(user_data)
    target_wallet = get_main_wallet(user_data)
    transactions = get_transactions_per_day(target_wallet)

    if yesterday is True:
        transactions = get_transactions_per_yesterday(target_wallet)

    # request.session['wallets'] = wallets
    # request.session['target_wallet'] = target_wallet

    context = {
        'title': 'Профиль',
        'form': form,
        'user': user_data,
        'wallets': wallets,
        'target_wallet': target_wallet,
        'transactions': transactions,
        'yesterday': yesterday
    }
    return render(request, 'finances/profile.html', context)


def create_more_wallet(request):
    """ Создание дополнительных счетов пользователя """
    
    target_wallet = get_main_wallet(request.user)

    if request.method == 'POST':
        form = CreateWalletForm(data=request.POST)
        if form.is_valid():
            user = request.user
            name = request.POST['name']
            currency = request.POST['currency']
            new_wallet_created = create_wallet(user, name, currency, False)
            if new_wallet_created:
                messages.success(request, 'Новый счет создан!')
                return HttpResponseRedirect(reverse('finances:profile'))
            else:
                messages.error(request, 'Не удалось создать счет')
                return HttpResponseRedirect(reverse('finances:profile'))
        else:
            messages.warning(request, 'Что-то пошло не так! Попробуйте снова.')
            return HttpResponseRedirect(reverse('finances:create_more_wallet'))
    else:
        form = CreateWalletForm()

    context = {
        'title': 'Создайте счет',
        'form': form,
        'target_wallet': target_wallet

    }
    return render(request, 'finances/create_wallet.html', context)

def update_wallet_data(request):
    """ Обновление существующего счета """
    wallet_data = get_any_wallet(request.session['wallet_id'])
    target_wallet = get_main_wallet(request.user)

    if request.method == 'POST':
        response = update_wallet(
            user=request.user,
            new_name=request.POST['name'],
            wallet_id=request.session['wallet_id'],
            target=True if 'target' in request.POST else False
        )
        if response:
            messages.success(request, 'Данные обновлены!')
            return HttpResponseRedirect(reverse('finances:profile'))
        else:
            messages.warning(request, 'Что-то пошло не так!')
            return HttpResponseRedirect(reverse('finances:update_wallet'))

    initial_data = {
        'name': wallet_data.name,
        'target': wallet_data.target
    }

    form = UpdateWalletForm(initial=initial_data)

    context = {
        'title': 'Измените данные',
        'form': form,
        'wallet': wallet_data,
        'target_wallet': target_wallet,
    }
    return render(request, 'finances/update_wallet.html', context)

def try_delete_wallet(request):
    wallet_id = request.session['wallet_id']
    user = request.user

    deleted = delete_wallet(user=user, wallet_id=wallet_id)

    if deleted:
        messages.success(request, 'Счет удален!')
        return HttpResponseRedirect(reverse('finances:profile'))
    else:
        messages.warning(request, 'Нельзя удалить единственный счет!')
        return HttpResponseRedirect(reverse('finances:update_wallet'))


def wallet_data(request):
    wallet_id = request.POST['wallet_id']

    request.session['wallet_id'] = wallet_id
    request.session.modified = True
    return redirect('finances:update_wallet')


def transactions_per_day(request):
    request.session['yesterday'] = False
    return redirect('finances:profile')

def transactions_per_yesterday(request):
    request.session['yesterday'] = True
    return redirect('finances:profile')


def income(request):
    type_transaction = True  # type(+)
    target_wallet = get_main_wallet(request.user)

    if request.method == 'POST':
        form = IncomeForm(data=request.POST)
        if form.is_valid():
            form_data = request.POST
            user_data = request.user
            try:
                transaction_save(form_data, user_data, type_transaction, target_wallet)
            except ValueError as ex:
                messages.warning(request, ex)
                return HttpResponseRedirect(reverse('finances:profile'))
            except:
                messages.warning(request, 'Не удалось сохранить операцию в базу :(')
                return HttpResponseRedirect(reverse('finances:profile'))
            else:
                balance_change(form_data, type_transaction, target_wallet)
                messages.success(request, 'Операция добавлена! Добавить еще?')
                return HttpResponseRedirect(reverse('finances:profile'))
        else:
            messages.warning(request, 'Что-то пошло не так!')
            return HttpResponseRedirect(reverse('finances:profile'))
    else:
        form = IncomeForm()

    context = {
        'title': 'Операция',
        'type_transaction': type_transaction,
        'target_wallet': target_wallet,
        'form': form
    }
    return render(request, 'finances/type-transaction.html', context)


def outline(request):
    type_transaction = False  # type (-)
    target_wallet = get_main_wallet(request.user)

    if request.method == 'POST':
        form = OutlineForm(data=request.POST)
        if form.is_valid():
            form_data = request.POST
            user_data = request.user
            try:
                transaction_save(form_data, user_data, type_transaction, target_wallet)
            except ValueError as ex:
                messages.warning(request, ex)
                return HttpResponseRedirect(reverse('finances:profile'))
            except:
                messages.warning(request, 'Не удалось сохранить операцию в базу :(')
                return HttpResponseRedirect(reverse('finances:profile'))
            else:
                balance_change(form_data, type_transaction, target_wallet)
                messages.success(request, 'Операция добавлена! Добавить еще?')
                return HttpResponseRedirect(reverse('finances:profile'))
        else:
            messages.warning(request, 'Что-то пошло не так!')
            return HttpResponseRedirect(reverse('finances:profile'))
    else:
        form = OutlineForm()

    context = {
        'title': 'Операция',
        'type_transaction': type_transaction,
        'target_wallet': target_wallet,
        'form': form
    }
    return render(request, 'finances/type-transaction.html', context)


def report(request):
    report_per = request.session.get('report_per')
    user_data = request.user
    target_wallet = get_main_wallet(request.user)

    transactions = get_transaction_for_report(report_per, user_data)
    context = {
        'title': 'Отчет',
        'report_per': report_per,
        'transactions': transactions,
        'user_data': user_data,
        'target_wallet': target_wallet,
    }
    return render(request, 'finances/report.html', context)

def report_per_day(request):
    request.session['report_per'] = 'day'
    return redirect('finances:report')
def report_per_week(request):
    request.session['report_per'] = 'week'
    return redirect('finances:report')
def report_per_month(request):
    request.session['report_per'] = 'month'
    return redirect('finances:report')


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:login'))

finances/templates/finances/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,400;0,600;1,200;1,400;1,600&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">

    {% block css %} {% endblock %}
    
    <title>{{ title }}</title>
</head>
<body class="black_bkg">
    <nav id="nav" class="gray_bkg">
        <a class="logo secondary_teal_text" href="{% url 'finances:profile' %}">
            MyFinance
        </a>
        <div class="nav-bar">
            <div class="balance">
                <div class="transaction-type-box">
                    <div class="transaction-btn">
                        <a href="{% url 'finances:income' %}" class="transaction-type-btn income">+</a>
                    </div>
                    <div class="transaction-btn">
                        <a href="{% url 'finances:outline' %}" class="transaction-type-btn outline">-</a>
                    </div>
                </div>
                <p>{{ target_wallet.name }} : </p>
                <p class="secondary_teal_text"> {{ target_wallet.balance }} {{ target_wallet.currency }}</p>
            </div>
            <a href="{% url 'investing:dashboard' %}">Инвестирование</a>
            <a href="{% url 'finances:report' %}">Полный отчет</a>
            <a href="{% url 'budgets:budgets' %}">Копилка</a>
            <a href="{% url 'finances:profile' %}">Профиль</a>
            {% block exit-btn %} {% endblock %}
        </div>
    </nav>

    {% if messages or form.errors %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert-box {% if message.tags == 'success' %} success {% else %} warning {% endif %} bd_radius gray_bkg">
            	    <p>{{ message }}</p>
                </div>
            {% endfor %}
        {% else %}
            <div class="alert-box warning bd_radius gray_bkg">
                <p>{{ form.non_field_errors }}</p>
            </div>
        {% endif %}
    {% endif %}

    {% block content %} {% endblock %}

    <footer class="gray_bkg">
        <div>Юсупов А. Т.</div>
        <div>2024</div>
        <div>Минск | БГУИР</div>
    </footer>
</body>
</html>

finances/templates/finances/create_wallet.html
{% extends 'finances/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/create_wallet.css' %}">
{% endblock %}

{% block content %}
    <main id="main">
        <section id="create_wallet" class="section gray_bkg bd_radius">
            <h1 class="section-title">Создайте новый счет:</h1>
            <form action="{% url 'finances:create_wallet' %}" method="post">
            {% csrf_token %}
                <div class="form-create-wallet">
                    <div class="form-input">
                        <label for="{{ form.name.id_for_label }}">Назовите счет:</label>
                        {{ form.name }}
                    </div>
                </div>
                <div class="form-create-wallet">
                    <div class="form-radio-input">
                        <label for="{{ form.currency.id_for_label }}">Категория:</label>
                        {{ form.currency }}
                    </div>
                </div>
                <div class="btns">
                    <div class="submit-btn">
                        <input type="submit" value="Добавить" class="btn primary_btn">
                    </div>
                    <div class="submit-btn">
                        <a href="{% url 'finances:profile' %}" class="btn second_btn">Отмена</a>
                    </div>
                </div>
            </form>
        </section>
    </main>
{% endblock %}

finances/templates/finances/profile.html
{% extends 'finances/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/profile.css' %}">
{% endblock %}

{% block exit-btn %}
    {% if user.is_authenticated %}
        {% if user.is_superuser or user.is_staff %}
            <a href="{% url 'admin:index' %}" class="btn primary_btn" style="margin-right: 10px">Админ-панель</a>
        {% endif %}
        <a href="{% url 'finances:logout' %}" class="btn second_btn">Выйти</a>
    {% endif %}
{% endblock %}

{% block content %}
    <main id="main">
        <section id="profile" class="section gray_bkg bd_radius">
            <h1 class="section-title">Личная информация</h1>
            <div class="wallets-main-box">
                {% for wallet in wallets %}
                    <form action="{% url 'finances:wallet_data' %}" method="POST">
                        {% csrf_token %}
                        <input 
                            type="text"
                            value="{{ wallet.id }}"
                            name="wallet_id"
                            style="display: none;"
                        />
                        <button type="submit" id="submit-btn" class="wallet-box {% if wallet.target %} target-wallet-box {% endif %}">
                            <h4>{{ wallet.name }}</h4>
                            <p>{{ wallet.balance }} {{target_wallet.currency}}</p>
                        </button>
                    </form>
                {% endfor %}
                
                <a href="{% url 'finances:create_wallet' %}" class="add-wallet-box">+</a>
            </div>
            <form action="{% url 'finances:profile' %}" method="post">
                {% csrf_token %}
                <div class="form-person-info">
                    <div class="form-input">
                        <label for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                    <div class="form-input">
                        <label for="{{ form.username.id_for_label }}">Логин</label>
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-person-info">
                    <div class="form-input">
                        <label for="{{ form.email.id_for_label }}">Почта</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="btns">
                    <div class="submit-btn">
                        <input type="submit" value="Применить" class="btn primary_btn">
                    </div>
                </div>
            </form>
        </section>
        <section id="report" class="section gray_bkg bd_radius">
            <h1 class="section-title">Отчет за
                <a href="{% url 'finances:transactions_per_yesterday' %}" class="{% if yesterday == True %}active primary_btn{% else %}second_btn{% endif %}">вчера</a>
                <a href="{% url 'finances:transactions_per_day' %}" class="{% if yesterday is False%}active primary_btn{% else %}second_btn{% endif %}">сегодня</a>
            </h1>
            <div class="report-box">
                {% if transactions %}
                    <div class="income-outlay-box">
                        <div class="transactions">
                            {% for transaction in transactions %}
                                <input type="checkbox" id="isexpanded" hidden />
                                <label class="transaction" for "isexpanded">
                                    <div class="transaction-base">
                                        <div class="category-ico-name">
                                            <div class="category-ico
                                            {% if transaction.type %} income {% else %} outline {% endif %}">
                                                <img src="{{ transaction.category.ico.url }}" alt="">
                                            </div>
                                            <div class="category-name">{{ transaction.category.name }}</div>
                                        </div>
                                        <div class="sum {% if transaction.type %} secondary_teal_text {% else %} primary_purple_text {% endif %}">
                                            {% if transaction.type %}+{% else %}-{% endif %}
                                            {{ transaction.sum }} {{ user_data.wallet_currency }}
                                        </div>
                                    </div>
                                    <div class="expandable">
                                        <p>{{ transaction.date|date:"d.m.y | d M"}}</p>
                                        {% if transaction.comment %}
                                            <p></br>{{ transaction.comment }}</p>
                                        {% endif %}
                                    </div>
                                </label>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    <h4 style="color: #CCC">Нет операций</h4>
                {% endif %}
            </div>
        </section>
    </main>
{% endblock %}

finances/templates/finances/report.html
{% extends 'finances/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/report.css' %}">
{% endblock %}
    
{% block content %}
    <main id="main">
        <section id="report" class="section gray_bkg bd_radius">
            <div class="section-title-btn">
                <h1 class="section-title">Отчет за
                    <a href="{% url 'finances:report_per_day' %}" class="{% if report_per == 'day' %}primary_btn active{% else %}second_btn{% endif %}">день</a>
                    <a href="{% url 'finances:report_per_week' %}" class="{% if report_per == 'week' %}primary_btn active{% else %}second_btn{% endif %}">неделю</a>
                    <a href="{% url 'finances:report_per_month' %}" class="{% if report_per == 'month' %}primary_btn active{% else %}second_btn{% endif %}">месяц</a>
                </h1>
                {% if transactions %}
                    <a href="{% url 'pdf_gen:pdf_generation' %}" style="margin-left: 30px;" class="btn primary_btn">
                        Скачать!
                    </a>
                {% endif %}
            </div>
            <div class="report-box">
                {% if transactions %}
                    <div class="income-outlay-box">
                        <div class="transactions">
                            {% for transaction in transactions %}
                            {% if transaction.type is True %}
                                <input type="checkbox" id="isexpanded" hidden />
                                <label class="transaction" for "isexpanded">
                                    <div class="transaction-base">
                                        <div class="category-ico-name">
                                            <div class="category-ico income">
                                                <img src="{{ transaction.category.ico.url }}" alt="">
                                            </div>
                                            <div class="category-name">{{ transaction.category.name }}</div>
                                        </div>
                                        <div class="sum secondary_teal_text">
                                            + {{ transaction.sum }} {{ transaction.wallet.currency }}
                                        </div>
                                    </div>
                                    <div class="expandable">
                                        <div>
                                            <p>{{ transaction.date|date:"d.m.y / d M" }}</p>
                                            <p>{{ transaction.wallet.name }}</p>
                                        </div> 
                                        {% if transaction.comment %}
                                            <p></br>{{ transaction.comment }}</p>
                                        {% endif %}
                                    </div>
                                </label>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="income-outlay-box">
                        <div class="transactions">
                            {% for transaction in transactions %}
                            {% if transaction.type is False %}
                                <input type="checkbox" id="isexpanded" hidden />
                                <label class="transaction" for "isexpanded">
                                    <div class="transaction-base">
                                        <div class="category-ico-name">
                                            <div class="category-ico outline">
                                                <img src="{{ transaction.category.ico.url }}" alt="">
                                            </div>
                                            <div class="category-name">{{ transaction.category.name }}</div>
                                        </div>
                                        <div class="sum primary_purple_text">
                                            - {{ transaction.sum }} {{ transaction.wallet.currency }}
                                        </div>
                                    </div>
                                    <div class="expandable">
                                        <div>
                                            <p>{{ transaction.date|date:"d.m.y / d M" }}</p>
                                            <p>{{ transaction.wallet.name }}</p>
                                        </div> 
                                        {% if transaction.comment %}
                                            <p></br>{{ transaction.comment }}</p>
                                        {% endif %}
                                    </div>
                                </label>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    <h4 style="color: #CCC">Нет операций</h4>
                {% endif %}
            </div>
        </section>
    </main>
{% endblock %}

finances/templates/finances/type-transaction.html
{% extends 'finances/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/transaction-page.css' %}">
{% endblock %}

{% block content %}
    <main id="main">
        <section id="transaction" class="section gray_bkg bd_radius">
            <h1 class="section-title">Опишите {% if type_transaction %}доход:{% else %}расход:{% endif %}</h1>
            <form action="{% if type_transaction %}{% url 'finances:income' %}{% else %}{% url 'finances:outline' %}{% endif %}" method="post">
            {% csrf_token %}
                <div class="form-transaction">
                    <div class="form-input">
                        <label for="{{ form.sum.id_for_label }}">Сумма:</label>
                        {{ form.sum }}
                    </div>
                    <div class="form-input">
                        <label for="">Счет:</label>
                        <input type="text" value="{{ target_wallet.name }}" id="wallet-input" readonly=True>
                    </div>
                </div>
                <div class="form-transaction">
                    <div class="form-input">
                        <label for="{{ form.category.id_for_label }}">Категория:</label>
                        {{ form.category }}
                    </div>
                </div>
                <div class="form-transaction">
                    <div class="form-input">
                        <label for="{{ form.comment.id_for_label }}">Комментарий:</label>
                        {{ form.comment }}
                    </div>
                </div>
                <div class="btns">
                    <div class="submit-btn">
                        <input type="submit" value="Добавить" class="btn primary_btn">
                    </div>
                    <div class="submit-btn">
                        <a href="{% url 'finances:profile' %}" class="btn second_btn">Отмена</a>
                    </div>
                </div>
            </form>
        </section>
    </main>
{% endblock %}