main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login, name='login'),
    path('user/', include('users.urls', namespace='user')),
    path('finances/', include('finances.urls', namespace='finances')),
    path('pdf_gen/', include('pdf_gen.urls', namespace='pdf_gen')),
    path('investing/', include('investing.urls', namespace='investing')),
    path('budgets/', include('budgets.urls', namespace='budgets'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import *

app_name = 'users'

urlpatterns = [
    path('', login, name='login'),
    path('registration/', registration, name='registration')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    # wallet = models.ForeignKey(to=Wallet, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.username} | Админ: {self.is_superuser}'


class Wallet(models.Model):
    name = models.CharField(max_length=50, default='Основной счет')
    currency = models.CharField(max_length=5, default='USD')
    balance = models.DecimalField(max_digits=14, decimal_places=2, default=0.00)
    target = models.BooleanField(default=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} | {self.name} / {self.currency} | Основной: {self.target}'



    



users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Логин'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Пароль'
    }))
    
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Имя пользователя'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'example@gmail.com'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Логин'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Пароль'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Подтвердите пароль'
    }))
    
    class Meta:
        model = User
        fields = (
            'first_name', 'email', 'username', 'password1', 'password2'
        )

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse

from users.forms import *
from users.services import create_wallet


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('finances:profile'))
    else:
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('finances:profile'))
        else:
            form = UserLoginForm()

    context = {
        'title': 'Авторизация',
        'form': form
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            user = request.POST['username']
            form.save()
            create_done = create_wallet(user)
            if create_done:
                messages.success(request, 'Регистрация прошла успешно! Войдите.')
            else:
                messages.warning(request, 'Не удалось создать базовый счет!')
            return HttpResponseRedirect(reverse('login'))
        else:
            messages.warning(request, 'Слабый пароль!')
            return HttpResponseRedirect(reverse('users:registration'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,400;0,600;1,200;1,400;1,600&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/users-main.css' %}">

    {% block css %} {% endblock %}
    
    <title>{{ title }}</title>
</head>
<body class="black_bkg">

    {% if messages or form.errors %}
        <div class="alert-box {% if messages %} success {% else %} warning {% endif %} bd_radius gray_bkg">
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% else %}
                <p>{{ form.errors }}</p>
            {% endif %}
        </div>
    {% endif %}

    {% block main %} {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static '/css/login.css' %}">
{% endblock %}

{% block main %}
    <main id="main">
        <section id="login" class="section gray_bkg bd_radius">
            <h1 class="section-title">Авторизация</h1>
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                <div class="form-user-info">
                    <div class="form-input">
                        <label for="{{ form.username.id_for_label }}">Логин</label>
                        {{ form.username }}
                    </div>
                    <div class="form-input">
                        <label for="{{ form.password.id_for_label }}">Пароль</label>
                        {{ form.password }}
                    </div>
                </div>
                <div class="btns">
                    <div class="submit-btn">
                        <input type="submit" value="Войти" class="btn primary_btn">
                    </div>
                    <div class="submit-btn">
                        <a href="{% url 'users:registration' %}" class="btn second_btn">Регистрация</a>
                    </div>
                </div>
            </form>
        </section>
    </main>
{% endblock %}

users/templates/users/registration.html
{% extends 'users/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}

{% block main %}
    <main id="main">
        <section id="registration" class="section gray_bkg bd_radius">
            <h1 class="section-title">Регистрация</h1>
            <form action="{% url 'user:registration' %}" method="post">
                {% csrf_token %}
                <div class="form-person-info">
                    <div class="form-input">
                        <label for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                    <div class="form-input">
                        <label for="{{ form.email.id_for_label }}">Почта</label>
                        {{ form.email }}
                    </div>
                    <div class="form-input">
                        <label for="{{ form.username.id_for_label }}">Логин</label>
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-user-info">
                    <div class="form-input">
                        <label for="{{ form.password1.id_for_label }}">Пароль</label>
                        {{ form.password1 }}
                    </div>
                    <div class="form-input">
                        <label for="{{ form.password2.id_for_label }}">Подтвердите пароль</label>
                        {{ form.password2 }}
                    </div>
                </div>
                <div class="btns">
                    <div class="submit-btn">
                        <input type="submit" value="Регистрация" class="btn primary_btn">
                    </div>
                    <div class="submit-btn">
                        <a href="{% url 'login' %}" class="btn second_btn">Войти</a>
                    </div>
                </div>
            </form>
        </section>
    </main>
{% endblock %}